---
name: K8s resources
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd $GITHUB_WORKSPACE && make docker-generate-kubernetes
      - uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.RW_PAT }}
